### ISSUE TITLE
Add database translations

### ISSUE THREAD

**Issue by turbedi** [po-devs/android-client#165]
So the database files are replaced by translated files (like the PC client does)

**Comment by MidwayMarshall** [comment]
Android swaps res by locale tag. The assets folder (where the pokemon files are) is not like this because you directly read them while in res there is a manager that hands you an identifier

**Comment by turbedi** [comment]
Do you think there is any other way to translate the database files?

**Comment by turbedi** [comment]
@MidwayMarshall Asking again, because it would be great to have translated db files for the new version: Do you think there is any other way to translate the database files?

**Comment by turbedi** [comment]
[Fixed](https://github.com/po-devs/android-client/commit/763a69d89e2566e806f5f9090104af961d15ec04)
