### ISSUE TITLE
PO APK Multilanguage

### ISSUE THREAD

**Issue by Radigar** [po-devs/android-client#168]
Hey there,

First of all forgive my poor English, I write this to propose a version of the apk in different languages, I mean names, texts battles, attacks etc ... Could this be possible?

Thank you very much greetings.

**Comment by DaniellMesquita** [comment]
Very good idea. I don't know if this app have a localization function, but it can be implemented. If already, I can create a Portuguese-BR language pack.

**Comment by MidwayMarshall** [comment]
These strings can be localized https://github.com/po-devs/android-client/blob/master/res/values/strings.xml

**Comment by DaniellMesquita** [comment]
@MidwayMarshall in which folder should I put the possible pt-br.xml file?

**Comment by MidwayMarshall** [comment]
res/values-pt/strings.xml

**Comment by DaniellMesquita** [comment]
I'm not talking about an Portuguese version of app, but an multilangual app which can have the max possible of languages to support.

**Comment by MidwayMarshall** [comment]
yes. and the app is in German French Spanish and English. UI strings are automatically localized to the phone's language setting if it can find viable translations otherwise it defaults to english

**Comment by DaniellMesquita** [comment]
Thank you! I'll fork, clone and translate now for a pull request. Too, I'll find Japanese and Chinese people to translate it.

**Comment by DaniellMesquita** [comment]
@Radigar in which language you need human translation?

**Comment by DaniellMesquita** [comment]
#171 Portuguese language.
