### ISSUE TITLE
Chinese language

### ISSUE THREAD

**Issue by DaniellPlasmmer** [po-devs/android-client#172]
Unlike the Desktop version (the Portuguese and possibly others have errors) this will have human translation. We need find Chinese's, Japanese's and Hindians for create translations.

**Comment by DaniellMesquita** [comment]
Unlike I do in Portuguese language, I'll automatically translate it with Bing Translator, and find chineses to rate the translation quality and suggest editions.

**Comment by turbedi** [comment]
I don't like the idea of using a web translator. I will create a thread on our forum and ask for help with translations for both Android and Windows client.

**Comment by aurist** [comment]
automatic web translators are not an acceptable substitute for real translations, especially when it comes to languages like chinese which function very differently from languages with the roman alphabet. we absolutely need human beings to do the translation. i've been hunting people for a while now but it's hard to find people with the language barrier.

**Comment by DaniellMesquita** [comment]
Thanks @turbedi and @aurist. We also need for Indians and Japaneses.

**Comment by DaniellMesquita** [comment]
Truly, we need find for all most popular languages. A topic for the translation of any languages that users know, except pt-br (we need pt of Portugal), es, fr, and others that are already done from human translations.

**Comment by MidwayMarshall** [comment]
The 122 languages of India Kappa?
The biggest issue of automatic translation is context. Google won't know which definition of the word we want :c
I've asked many Chinese/English speakers to translate the app but everyone has refused so far

**Comment by DaniellMesquita** [comment]
This is the point, @MidwayMarshall. Find ONE people are a trouble. But from TEN people ONE accept, is an very much bigger problem.

**Comment by DaniellPlasmmer** [comment]
?

**Comment by MidwayMarshall** [comment]
What is the confusion. Chinese translations were added

**Comment by DaniellPlasmmer** [comment]
Then, please do reference to this issue.

**Comment by Fuzzysqurl** [comment]
You're not my supervisor.

**Comment by DaniellPlasmmer** [comment]
I don't see a commit with chinese translations added in this project.

**Comment by Fuzzysqurl** [comment]
You had a 1 in 7 chance to choose any non-merge commit in the past 24 hours and find it. You had a 1 in 2 chance if you excluded anything that clearly stated what it did and wasn't the translation. https://github.com/po-devs/android-client/commit/763a69d89e2566e806f5f9090104af961d15ec04

**Comment by DaniellPlasmmer** [comment]
Yes I've accessed that commit, searched for "ch" and nothing found. Thanks for the link and technical/statistic data that can make me smarter like you.

**Comment by Fuzzysqurl** [comment]
A freemason drew it for me.

**Comment by MidwayMarshall** [comment]
The translation tag for Chinese is "zh" on android not "ch"
https://github.com/po-devs/android-client/blob/master/res/values-zh/strings.xml

**Comment by DaniellPlasmmer** [comment]
Sorry for it, @MidwayMarshall.
Thanks.
