### ISSUE TITLE
Update to Gen 7

### ISSUE THREAD

**Issue by turbedi** [po-devs/android-client#200]
Things that need to be done:

- [x] Update database (I tried to do it but it currently causes a crash when opening teambuilder. Log: http://pastebin.com/PBptfNHP

- [x] Z-Moves

- [x] Don't edit DVs when selecting Hidden Power types (should be done in the gen-7 branch, but I wasn't able to test it yet, because of the crash)

- [x] Send Hidden Power data to the server (if I understood the changes correctly, we now also send the Hidden Power type to the server. No idea how this excatly works)

- [x] Other things that I have forgotten about

**Comment by MidwayMarshall** [comment]
https://github.com/po-devs/android-client/wiki/Updating-Database

**Comment by turbedi** [comment]
FeelsBadMan

**Comment by turbedi** [comment]
Still crashing (or I am doing something wrong ._.)

**Comment by VeteranPadgett** [comment]
Your db stuff was fine. The client was just getting messed up by Mimikyu-Broken form. Made a PR that should fix it.

**Comment by MidwayMarshall** [comment]
The db is not fine, it had a new line in pokemons.txt that broke it. It has mismatching stats and it also has mismatching abilities that are causing it to crash.
If a pokemon is not released it does not need info in the stats.txt nor does it need stuff in the ability1-3

**Comment by turbedi** [comment]
Client isn't crashing anymore, thanks Midway.
Noticed another bug: [This code](https://github.com/po-devs/android-client/blob/gen-7/src/com/podevs/android/poAndroid/pokeinfo/ItemInfo.java#L240-L244) removes all the items and only berries are remaining.

**Comment by VeteranPadgett** [comment]
Sorry, I wasn't sure if Mimikyu-Broken needed added to db or something made to handle that situation.
