### ISSUE TITLE
Background color error

### ISSUE THREAD

**Issue by IceKirby** [po-devs/android-client#278]
This line is causing a few errors: https://github.com/po-devs/android-client/blob/master/src/com/podevs/android/utilities/MyHtml.java#L502

First, if the color passed to it has less than 6 characters, the client will crash (so something like `<background color='red'>Testing</background>` will crash because it's trying to substring(6) the 'red' string.

Also, even if the color is something like `#ff0000`, the resulting color will be black because the first 6 characters have been removed. If I use something like `blabla#ff000000` the tag will work normally since the 'blabla' part gets removed.

I don't know if that line is supposed to have some other purpose, so I'm reporting as an issue instead of creating a PR.
If the crash dump log is necessary I can post.

**Comment by turbedi** [comment]
It might be a copy/paste error from [here](https://github.com/po-devs/android-client/blob/817fc499e1e4b75b8ec5d7f854bda04e3e167c0d/src/com/podevs/android/utilities/MyHtml.java#L393). If removing the line fixes the error and doesn't cause any other issues, feel free to open a PR
