### ISSUE TITLE
Problem with Hidden Power's Types in 2ª GEN

### ISSUE THREAD

**Issue by eltonsantos** [po-devs/android-client#68]
When i choose Hidden Power and choose the type after on click OK, dont save and ever choose Dark's Type =/
Need fix it, priority urgentily
Please HPs is major priority > . <

**Comment by Withoutatrace** [comment]
I ended up writing out an algorithm that might fix it a few weeks ago, I'll apply it and see if it resolves the issue.

**Comment by MidwayMarshall** [comment]
https://github.com/po-devs/android-client/commit/130aec3ae84514dc44a2be25067beecd69589944
